apiVersion: v1
kind: Service
metadata:
    name: saxonydevopstestsqldeployment
spec:
    type: LoadBalancer
    ports:
    - port: 1433 
    selector:
        app: saxonydevopstestsqldeployment